algoritmo "Meu primeiro algoritimo"
var
//SEÇÃO DE DECLARAÇÃO DE VARIAVEIS
  name:caractere
  idade:inteiro
  altura:real
  casado:logico
inicio
//SEÇÃO DE COMANDOS
    escreva("Seu nome: ")
    leia(name)
    escreva("Digite sua idade: ")
    leia(idade)
    escreva("Digite sua Altura: ")
    leia(altura)
    Escreval("Seu nome e ",name, " sua idade e " ,idade, "e sua altura e " ,altura)
    
fimalgoritmo
